# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 351900aea100b8cc413d9354077b7d8fe4c0b13dfe931852bf27e67b66c4f16f6e8f8ae7877560d46e0f483a0f93bba5c955cd3cb1686d4492289556b8883c29

test:
  secret_key_base: c90896bcbfbd3556e08456898510b08792549d2ff1dec60808a398cdac0ee693d4a65848c22e43ffc0309a0ca252d52b0dbafc36d1170f57354d123e9d805f87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
